baseURL = "https://peter.gs"
languageCode = "en-us"
title = "petergs"
theme = "lekh"

[params]
Name = "Peter Stratis"
About = "Hi! I'm Peter â€” a Systems Administrator in Brooklyn, NY with an interest in cybersecurity." 
Email = "contact@peter.gs"
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/petergs"

[[params.profiles]]
name = "Twitter"
url = "https://twitter.com/peter__gs"

[[params.profiles]]
name = "LinkedIn"
url = "https://linkedin.com/in/petergs"
